export const RES_PRODUCTS_ERRORED = 'RES_PRODUCTS_ERRORED';
export const RES_PRODUCTS_IS_LOADING = 'RES_PRODUCTS_IS_LOADING';
export const RES_PRODUCTS_FETCH_DATA_SUCCESS = 'RES_PRODUCTS_FETCH_DATA_SUCCESS';
