export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CHECK_LOCALSTORAGE = 'CHECK_LOCALSTORAGE';
export const ADDITION_QQT_PRODUCT = 'ADDITION_QQT_PRODUCT';
export const SUBTRACTION_QTT_PRODUCT = 'SUBTRACTION_QTT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const STICKY_BASKET = 'STICKY_BASKET';